name: Python Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Flask
        run: pip install flask

      - name: Verificar sintaxis
        run: python -m py_compile app.py

      - name: Mensaje
        run: echo "Workflow ejecutado correctamente"